--Exclusão de Tabelas
DROP TABLE T_USUARIO CASCADE CONSTRAINTS PURGE;
DROP TABLE T_CONTA CASCADE CONSTRAINTS PURGE;
DROP TABLE T_CARTAO_CREDITO CASCADE CONSTRAINTS PURGE;
DROP TABLE T_PAGAMENTO CASCADE CONSTRAINTS PURGE;
DROP TABLE T_TRANSACAO CASCADE CONSTRAINTS PURGE;
DROP TABLE T_RECEITA CASCADE CONSTRAINTS PURGE;
DROP TABLE T_TRANSFERENCIA CASCADE CONSTRAINTS PURGE;
DROP TABLE T_DESPESA CASCADE CONSTRAINTS PURGE;
DROP TABLE T_DESPESA_CONTA CASCADE CONSTRAINTS PURGE;
DROP TABLE T_DESPESA_CARTAO CASCADE CONSTRAINTS PURGE;
--Criando as Tabelas
CREATE TABLE T_USUARIO(
codigo_usuario INTEGER NOT NULL,
usuario VARCHAR2(50) NOT NULL,
email VARCHAR2(254) NOT NULL,
senha VARCHAR2(100) NOT NULL,
foto BLOB
);
CREATE TABLE T_CONTA(
codigo_conta INTEGER NOT NULL,
codigo_usuario INTEGER NOT NULL,
nome VARCHAR2(50) NOT NULL,
icone BLOB NOT NULL,
tipo_conta INTEGER NOT NULL,
valor FLOAT(10) NOT NULL
);
CREATE TABLE T_CARTAO_CREDITO(
codigo_cartao INTEGER NOT NULL,
codigo_usuario INTEGER NOT NULL,
nome VARCHAR2(50) NOT NULL,
icone BLOB NOT NULL,
limite FLOAT(10) NOT NULL
);
CREATE TABLE T_PAGAMENTO(
codigo_conta INTEGER NOT NULL,
codigo_cartao INTEGER NOT NULL,
data DATE NOT NULL,
valor FLOAT(10) NOT NULL
);
CREATE TABLE T_TRANSACAO(
codigo_transacao INTEGER NOT NULL,
"DATA" DATE NOT NULL,
valor FLOAT(10) NOT NULL,
hora DATE,
anotacao VARCHAR2(500)
);
CREATE TABLE T_RECEITA(
codigo_receita INTEGER NOT NULL,
codigo_transacao INTEGER NOT NULL,
codigo_conta INTEGER NOT NULL,
nome VARCHAR2(50) NOT NULL,
categoria INTEGER
);
CREATE TABLE T_TRANSFERENCIA(
codigo_transferencia INTEGER NOT NULL,
codigo_transacao INTEGER NOT NULL,
codigo_conta INTEGER NOT NULL
);
CREATE TABLE T_DESPESA(
codigo_despesa INTEGER NOT NULL,
codigo_transacao INTEGER NOT NULL,
nome VARCHAR2(50) NOT NULL,
categoria INTEGER NOT NULL,
icone BLOB
);
CREATE TABLE T_DESPESA_CONTA(
codigo_despesa INTEGER NOT NULL,
codigo_conta INTEGER NOT NULL
);
CREATE TABLE T_DESPESA_CARTAO(
codigo_despesa INTEGER NOT NULL,
codigo_cartao INTEGER NOT NULL
);
--Exclusão de Sequências
DROP SEQUENCE SQ_PK_CODIGO_USUARIO;
DROP SEQUENCE SQ_PK_CODIGO_CONTA;
DROP SEQUENCE SQ_PK_CODIGO_CARTAO;
DROP SEQUENCE SQ_PK_TRANSACAO;
DROP SEQUENCE SQ_PK_RECEITA;
DROP SEQUENCE SQ_PK_TRANSFERENCIA;
DROP SEQUENCE SQ_PK_DESPESA;
--Criação de Sequências
CREATE SEQUENCE SQ_PK_CODIGO_USUARIO NOCACHE;
CREATE SEQUENCE SQ_PK_CODIGO_CONTA NOCACHE;
CREATE SEQUENCE SQ_PK_CODIGO_CARTAO NOCACHE;
CREATE SEQUENCE SQ_PK_TRANSACAO NOCACHE;
CREATE SEQUENCE SQ_PK_RECEITA NOCACHE;
CREATE SEQUENCE SQ_PK_TRANSFERENCIA NOCACHE;
CREATE SEQUENCE SQ_PK_DESPESA NOCACHE;
--Alteração de Tabelas
--Alteração para Chaves Primárias
ALTER TABLE T_USUARIO ADD CONSTRAINT PK_CODIGO_USUARIO PRIMARY KEY(codigo_usuario);
ALTER TABLE T_CONTA ADD CONSTRAINT PK_CODIGO_CONTA PRIMARY KEY(codigo_conta);
ALTER TABLE T_CARTAO_CREDITO ADD CONSTRAINT PK_CODIGO_CARTAO PRIMARY KEY(codigo_cartao);
ALTER TABLE T_PAGAMENTO ADD CONSTRAINT PK_T_PAGAMENTO PRIMARY KEY(codigo_conta,codigo_cartao);
ALTER TABLE T_TRANSACAO ADD CONSTRAINT PK_CODIGO_TRANSACAO PRIMARY KEY(codigo_transacao);
ALTER TABLE T_RECEITA ADD CONSTRAINT PK_T_RECEITA PRIMARY KEY(codigo_receita);
ALTER TABLE T_TRANSFERENCIA ADD CONSTRAINT PK_T_TRANSFERENCIA PRIMARY KEY(codigo_transferencia);
ALTER TABLE T_DESPESA ADD CONSTRAINT PK_T_DESPESA PRIMARY KEY(codigo_despesa);
ALTER TABLE T_DESPESA_CONTA ADD CONSTRAINT PK_T_DESPESA_CONTA PRIMARY KEY(codigo_despesa,codigo_conta);
ALTER TABLE T_DESPESA_CARTAO ADD CONSTRAINT PK_T_DESPESA_CARTAO PRIMARY KEY(codigo_despesa,codigo_cartao);
--ALteração para Chaves Estrangeiras
ALTER TABLE T_CONTA ADD CONSTRAINT FK_CODIGO_USUARIO_T_CONTA FOREIGN KEY(codigo_usuario) REFERENCES T_USUARIO(codigo_usuario);
ALTER TABLE T_CARTAO_CREDITO ADD CONSTRAINT FK_CODIGO_USUARIO_T_CARTAO FOREIGN KEY(codigo_usuario) REFERENCES T_USUARIO(codigo_usuario);
ALTER TABLE T_PAGAMENTO ADD CONSTRAINT FK_T_PAGAMENTO_CODIGO_CONTA FOREIGN KEY(codigo_conta) REFERENCES T_CONTA(codigo_conta);
ALTER TABLE T_PAGAMENTO ADD CONSTRAINT FK_T_PAGAMENTO_CODIGO_CARTAO FOREIGN KEY(codigo_cartao) REFERENCES T_CARTAO_CREDITO(codigo_cartao);
ALTER TABLE T_RECEITA ADD CONSTRAINT FK_T_RECEITA_CODIGO_TRANSACAO FOREIGN KEY(codigo_transacao) REFERENCES T_TRANSACAO(codigo_transacao);
ALTER TABLE T_RECEITA ADD CONSTRAINT FK_T_RECEITA_CODIGO_CONTA FOREIGN KEY(codigo_conta) REFERENCES T_CONTA(codigo_conta);
ALTER TABLE T_TRANSFERENCIA ADD CONSTRAINT FK_T_TRANSFERENCIA_CODIGO_TRANSACAO FOREIGN KEY(codigo_transacao) REFERENCES T_TRANSACAO(codigo_transacao);
ALTER TABLE T_TRANSFERENCIA ADD CONSTRAINT FK_T_TRANSFERENCIA_CODIGO_CONTA FOREIGN KEY(codigo_conta) REFERENCES T_CONTA(codigo_conta);
ALTER TABLE T_DESPESA ADD CONSTRAINT FK_T_DESPESA FOREIGN KEY(codigo_transacao) REFERENCES T_TRANSACAO(codigo_transacao);
ALTER TABLE T_DESPESA_CONTA ADD CONSTRAINT FK_T_DESPESA_CONTA_CODIGO_CONTA FOREIGN KEY(codigo_conta) REFERENCES T_CONTA(codigo_conta);
ALTER TABLE T_DESPESA_CONTA ADD CONSTRAINT FK_T_DESPESA_CONTA_CODIGO_DESPESA FOREIGN KEY(codigo_despesa) REFERENCES T_DESPESA(codigo_despesa);
ALTER TABLE T_DESPESA_CARTAO ADD CONSTRAINT FK_T_DESPESA_CARTAO_CODIGO_DESPESA FOREIGN KEY(codigo_despesa) REFERENCES T_DESPESA(codigo_despesa);
ALTER TABLE T_DESPESA_CARTAO ADD CONSTRAINT FK_T_DESPESA_CARTAO_CODIGO_CARTAO FOREIGN KEY(codigo_cartao) REFERENCES T_CARTAO_CREDITO(codigo_cartao);
--Alteração para Constraints Default
ALTER TABLE T_USUARIO MODIFY codigo_usuario DEFAULT SQ_PK_CODIGO_USUARIO.NEXTVAL;
ALTER TABLE T_CONTA MODIFY codigo_conta DEFAULT SQ_PK_CODIGO_CONTA.NEXTVAL;
ALTER TABLE T_CARTAO_CREDITO MODIFY codigo_cartao DEFAULT SQ_PK_CODIGO_CARTAO.NEXTVAL;
ALTER TABLE T_TRANSACAO MODIFY codigo_transacao DEFAULT SQ_PK_TRANSACAO.NEXTVAL;
ALTER TABLE T_RECEITA MODIFY codigo_receita DEFAULT SQ_PK_RECEITA.NEXTVAL;
ALTER TABLE T_TRANSFERENCIA MODIFY codigo_transferencia DEFAULT SQ_PK_TRANSFERENCIA.NEXTVAL;
ALTER TABLE T_DESPESA MODIFY codigo_despesa DEFAULT SQ_PK_DESPESA.NEXTVAL;
--Alteração para Constraints Unique
ALTER TABLE T_USUARIO ADD CONSTRAINT UN_USUARIO UNIQUE(usuario);
ALTER TABLE T_USUARIO ADD CONSTRAINT UN_EMAIL UNIQUE(email);